drone_inventory/authentication/routes.py
# package imports
from flask import Blueprint, flash, redirect, render_template, request, redirect,url_for
from flask_login import login_user, logout_user, current_user,login_required

#project file imports
from drone_inventory.forms import UserLoginForm
from drone_inventory.models import User, db, check_password_hash

auth = Blueprint('auth', __name__,template_folder = 'auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email,password)

            #Add User into Database
            user = User(email, password=password)
            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account for {email}.','user-created')
            return redirect(url_for('auth.signin'))

    except:
        raise Exception('Invalid Form Data: Please check your form')

    return render_template('signup.html', form=form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email,password)

            # Query user table for users with this info
            logged_user = User.query.filter(User.email == email).first()
            # Check if logged_user and password == password
            if logged_user and check_password_hash(logged_user.password,password):
                login_user(logged_user)
                flash('You were successfully logged in')
                return redirect(url_for('site.profile'))
            else:
                flash('Your Email/Password is incorrect.','auth-failed')
                return redirect(url_for('auth.signin'))

    except:
        raise Exception('Invalid Form Data: Please check your form.')

    return render_template('signin.html', form = form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

drone_inventory/site/routes.py
from flask import Blueprint, render_template
from flask_login.utils import login_required

site = Blueprint('site', __name__, template_folder='site_templates')

"""
Note that in the above code some arguments are specified the Blueprint object,
The first argument, 'site' is the Blueprint's name,
which is used by Flask's routing mechanism.
The second argument, __name__, is the Blueprint's import name,
which Flask uses to locate the Blueprint's resource
"""

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

drone_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Drone Inventory API</title>
</head>
<body>

    <!-- Navbar here -->
    <nav class="ct-nav">
        <div><img src="../static/images/Coding Drones Logo.png"></div>

        <!-- Nav Items -->
        <div>
            <ul id="horizontal-list">
                <a href="{{ url_for('site.home') }}">
                    <li>The Coding Drones Project</li>
                </a>
                <a href="">
                    <li>Donate</li>
                </a>
                <a href="{{ url_for('site.profile') }}">
                    <li>Profile</li>
                </a>
                {% if current_user.is_authenticated %}
                <a href="{{  url_for('auth.logout') }}">
                    <li>Log out</li>
                </a>
                {% else %}
                <a href="{{ url_for('auth.signup') }}">
                    <li>Sign Up</li>
                </a>
                <a href="{{ url_for('auth.signin') }}">
                    <li>Sign In</li>
                </a>
                {% endif %}
            </ul>
        </div>

        
    </nav>
    <!-- End of navbar -->

    {% block content %}
    {% endblock content %}




<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

drone_inventory/templates/forms.html
<!--HTML produced by the UserLoginForm-->

<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class='form-control',placeholder='Place email here...') }}
        </fieldset>
        <fieldset id="password-field">
            {{ form.password.label }}
            {{ form.password(class='form-control',placeholder='Password Here...') }}
        </fieldset>
        <fieldset id="confirm-field">
            {{ form.confirm.label }}
            {{ form.confirm(class='form-control',placeholder='Confirm Password') }}
        </fieldset>

        {{ form.submit_button(class = 'btn btn-primary btn-block') }}
    </div>
</form>